theme = "onedark"

[editor]
line-number = "relative"
shell =  ["fish"]
cursorline = true
bufferline = "always"
color-modes = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.statusline]
left = ["mode", "spinner", "workspace-diagnostics"]
center = ["read-only-indicator", "file-name"]
right = ["selections", "spacer", "position-percentage"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-inlay-hints = true

[keys.normal]
A-h = ":buffer-previous"
A-l = ":buffer-next"
A-del = ":buffer-close"
