[language-server.tinymist]
command = "tinymist"
config = { exportPdf = "onType", formatterMode = "typstyle" }

[[language]]
name = "rust"
formatter = { command = "rustfmt" }
auto-format = true


[language-server.rust-analyzer.config]
checkOnSave = { command = "clippy", extraArgs = ["--", "-w", "clippy::pendantic"] }
procMacro = { enable = true }
